uploads = []
generated = []

[[outputs]]
id = "MKgx4EG1dklyz5LfJri5L"
uri = "file://ihflow-frontend.zip"
type = "unspecified"
title = "ihflow-frontend.zip — كل ملفات المشروع"

[[outputs]]
id = "-VXUy2xVVmozM7VybKbe0"
uri = "file://index.html.txt"
type = "text"
title = "index.html"
